platform :ios, '9.0'

target 'react_native_mobx' do
  # this is very important to have!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'IQKeyboardManager', '~>6.3.0'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-html-to-pdf', :path => '../node_modules/react-native-html-to-pdf'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'JCoreRN', :path => '../node_modules/jcore-react-native'

  pod 'JPushRN', :path => '../node_modules/jpush-react-native'

  pod 'RNImageMarker', :path => '../node_modules/react-native-image-marker'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-print', :path => '../node_modules/react-native-print'

  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

end

# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
